package model.pojo;
// Generated 2016-03-08 10:50:28 by Hibernate Tools 4.3.1



/**
 * Uczen generated by hbm2java
 */
public class Uczen  implements java.io.Serializable {


     private int id;
     private String imie;
     private String nazwisko;

    public Uczen() {
    }

	
    public Uczen(int id) {
        this.id = id;
    }
    public Uczen(int id, String imie, String nazwisko) {
       this.id = id;
       this.imie = imie;
       this.nazwisko = nazwisko;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getImie() {
        return this.imie;
    }
    
    public void setImie(String imie) {
        this.imie = imie;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }




}


